services:
  backend:
    image: node:20-alpine
    container_name: transcendence-backend-dev
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ../backend/api/transcendence-api-gateway:/app
      - backend-node-modules:/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - HOST=0.0.0.0
    networks:
      - transcendence-network

  prometheus:
    image: prom/prometheus:latest
    container_name: transcendence-prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-dev:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - transcendence-network
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: transcendence-grafana-dev
    ports:
      - '5001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - transcendence-network
    volumes:
      - grafana-data-dev:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  transcendence-network:
    driver: bridge

volumes:
  backend-node-modules:
  prometheus-data-dev:
  grafana-data-dev: